datasets:
  data_faces:
    type: imagefolder
    root: ./Data
    splits:
      train: train
      val: test
      test: test
    classes:
      - Angry
      - Fear
      - Happy
      - Sad
      - Suprise
    input_size: [224, 224]
    normalization:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    force_grayscale: true
    auto_split:
      seed: 1337
      ratios:
        train: 0.7
        val: 0.2
        test: 0.1
